### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by feyzullahyildiz** [feyzullahyildiz/geoserver-wms-viewer#9]
TODOS: 

- [ ] Use typescript
- [ ]  Convert css files to scss
- [ ] Make stylesheet files are scoped
- [ ] Use a bundler
- [x] Use github pages
- [ ] Write unit, e2e test and connect to Travis or CircleCI
